## **Tensors in PyTorch**

- PyTorch is a deep learning framework used to create tensors, neural networks and AI models. It provides GUI support and automatic differentiation.

- Keywords
    - torch : tensor operations
    - nn : neural networks
    - optim : optimization algorithms

In [1]:
# import the libraries
import torch
import torch.nn as nn
import torch.optim as optim

### **Check the PyTorch's version**

In [2]:
print(torch.__version__)

2.10.0+cpu


### **Confirm the GPU availability**

In [3]:
# GPU increases the speed of the model training significantly
# cuda -> GPU available, cpu -> CPU execution

device = torch.device(
    'cuda' if torch.cuda.is_available()
    else 'cpu')

print(device)

cpu


### **Create the tensors**

In [4]:
# Tensors is the core data structure in pytorch, it is quite similar to NumPy arrays

x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [5]:
# To confirm if this is a tensor or not
type(x)

torch.Tensor

In [6]:
# Using the "empty" command. It creates a tensor of a specified shape filled with uninitialized data.

a = torch.empty(2, 3)
print(a)

tensor([[nan, nan, nan],
        [nan, nan, nan]])


In [7]:
# To make a tensor purely out of 0s we use "zeros".

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# To make a tensor purely out of 1s we use "ones".

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# "Rand" in PyTorch is used to create a tensor of a given shape filled with random numbers from a uniform distribution on the interval.

torch.rand(6, 2)

tensor([[0.4369, 0.8959],
        [0.4946, 0.8396],
        [0.1402, 0.9668],
        [0.2124, 0.6399],
        [0.7149, 0.9761],
        [0.9420, 0.5371]])

In [10]:
# "Manual_seed" used to set the seed for the random number generator (RNG) across all devices, including the CPU and CUDA.
# We use it with torch.rand() to creates random number (it basically provides a structure for the seeds to be generated).

torch.manual_seed(500)
torch.rand(2, 3)

tensor([[0.5820, 0.1338, 0.7995],
        [0.3071, 0.6526, 0.6105]])

In [11]:
# One more example

torch.manual_seed(500)
torch.rand(4,5)

tensor([[0.5820, 0.1338, 0.7995, 0.3071, 0.6526],
        [0.6105, 0.1575, 0.6983, 0.7883, 0.7981],
        [0.4593, 0.8997, 0.2518, 0.5648, 0.0302],
        [0.5930, 0.6386, 0.4795, 0.6030, 0.7351]])

In [12]:
# Other Useful Tensor Creation Commands in PyTorch

# torch.arange(start, end, step) -> Creates a tensor with values starting from 'start' up to 'end-1' using the given step size.
print("\n using arange ->", torch.arange(0,10,2))

# torch.linspace(start, end, steps) -> Creates a tensor with a fixed number of evenly spaced values between start and end.
print("\n using linspace ->", torch.linspace(0, 10, 7))

# torch.eye(n) -> Creates an n × n identity matrix with 1s on the diagonal and 0s elsewhere.
print("\n using eye ->", torch.eye(5))

# torch.full(size, value) -> Creates a tensor of the given shape filled entirely with the specified value.
print("\n using full ->", torch.full((3, 3), 5))


 using arange -> tensor([0, 2, 4, 6, 8])

 using linspace -> tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])

 using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

 using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# **Tensor Shape and Tensor Creation in PyTorch**

### Creating Tensors in Different Ways

In [13]:
torch.tensor([[1,2,3],[4,5,6]])

#Creates a tensor from a Python list.
#Shape → (2, 3) → 2 rows and 3 columns.

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
torch.arange(0, 10, 2)

#Creates values from 0 to 10 (excluding 10) with a step size of 2.
# Output → 0, 2, 4, 6, 8
# Useful for generating evenly spaced integer values.

tensor([0, 2, 4, 6, 8])

In [15]:
torch.linspace(0, 10, 10)

# Creates 10 equally spaced values between 0 and 10 (including both).
# Commonly used in mathematics, plotting, and ML experiments.

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [16]:
torch.eye(5)

# Creates a 5 × 5 identity matrix.
# Diagonal elements are 1, all other elements are 0.
# Useful in linear algebra operations.

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.full((3, 3), 5)

# Creates a 3 × 3 tensor filled entirely with 5
# Useful when constant values are needed.

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [18]:
# Tensor Shape
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [19]:
torch.Size([2, 3])

# Represents the dimensions of the tensor. Here:
# 2 → Number of rows
# 3 → Number of columns

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

# Creates a tensor with the same shape as x.
# Values are uninitialized (random garbage values).
# Very fast, but values are meaningless until assigned.

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.zeros_like(x)

# Creates a tensor with the same shape as x, filled with 0s.

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

# Creates a tensor with the same shape as x, filled with 1s.

tensor([[1, 1, 1],
        [1, 1, 1]])

In [81]:
torch.rand_like(x, dtype=torch.float32)

# Creates a tensor with the same shape as x.
# Filled with random values between 0 and 1.
# dtype=torch.float32 sets the data type to 32-bit floating point.

tensor([[0.3933, 0.1042],
        [0.3993, 0.4203]])

# **Tensor Data Types**

In [24]:
# find data type formate : "name of tensor.dtype"
x.dtype

torch.int64

In [25]:
# assign data type (changes the data type from one to another or can say forces)

torch.tensor([1.0, 2.0, 3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1, 2, 3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# **Datatypes and it's Descriptions**

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# **Mathematical Operations**

### 1. Scalar operation

In [28]:
x = torch.rand(2,2)
x

tensor([[0.6037, 0.1817],
        [0.3849, 0.8164]])

In [29]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.3644, 0.0330],
        [0.1482, 0.6665]])

### 2. Element wise operation

In [30]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.3086, 0.4626, 0.7494],
        [0.9410, 0.0619, 0.6229]])
tensor([[0.8790, 0.6113, 0.6402],
        [0.0360, 0.4153, 0.2534]])


In [31]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3086, 0.4626, 0.1091],
        [0.0048, 0.0619, 0.1161]])

In [32]:
c = torch.tensor([1, -2, 3, -4])

In [33]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [34]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [82]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4, 1.5])

In [83]:
# round
torch.round(d)

tensor([2., 2., 4., 4., 2.])

In [84]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5., 2.])

In [85]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4., 1.])

In [39]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [40]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[2., 1., 9.],
        [1., 9., 2.]])

In [41]:
torch.sum(e, dim=0)

tensor([ 3., 10., 11.])

In [42]:
# sum
torch.sum(e)

# adds all the elements of the tensor together and returns the total sum.

tensor(24.)

In [43]:
# mean
torch.mean(e)
# mean along col

torch.mean(e, dim=0)

tensor([1.5000, 5.0000, 5.5000])

In [44]:
# median
torch.median(e)

tensor(2.)

In [45]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [46]:
# product
torch.prod(e)

tensor(324.)

In [47]:
# standard deviation
torch.std(e)

tensor(3.8987)

In [48]:
# variance
torch.var(e)

tensor(15.2000)

In [49]:
# argmax
torch.argmax(e)

tensor(2)

In [50]:
# argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [51]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[4, 1, 7],
        [7, 9, 9]])
tensor([[7, 9],
        [2, 5],
        [3, 4]])


In [52]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 51,  69],
        [ 94, 144]])

In [53]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [54]:
# transpose
torch.transpose(f, 0, 1)

tensor([[4, 7],
        [1, 9],
        [7, 9]])

In [55]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
print(h)

tensor([[1., 9., 6.],
        [2., 8., 7.],
        [1., 2., 8.]])


In [56]:
# determinant
torch.det(h)

tensor(-55.0000)

In [57]:
# inverse
torch.inverse(h)

tensor([[-0.9091,  1.0909, -0.2727],
        [ 0.1636, -0.0364, -0.0909],
        [ 0.0727, -0.1273,  0.1818]])

### 5. Comparison operations

In [58]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[2, 3, 0],
        [8, 0, 4]])
tensor([[2, 2, 7],
        [9, 7, 0]])


In [59]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[False,  True,  True],
        [ True,  True,  True]])

### 6. Special functions

In [60]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(k)

tensor([[1., 4., 3.],
        [4., 6., 1.]])


In [61]:
# log
torch.log(k)

tensor([[0.0000, 1.3863, 1.0986],
        [1.3863, 1.7918, 0.0000]])

In [62]:
# exp
torch.exp(k)

tensor([[  2.7183,  54.5981,  20.0855],
        [ 54.5981, 403.4288,   2.7183]])

In [63]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 2.0000, 1.7321],
        [2.0000, 2.4495, 1.0000]])

In [64]:
# sigmoid scaling bw 0 and 1
torch.sigmoid(k)

tensor([[0.7311, 0.9820, 0.9526],
        [0.9820, 0.9975, 0.7311]])

In [65]:
# softmax scaling bw 0 and 1 with sum of all elements as 1
torch.softmax(k, dim=0)

tensor([[0.0474, 0.1192, 0.8808],
        [0.9526, 0.8808, 0.1192]])

# **Inplace Operations**

In [66]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9695, 0.5142, 0.5998],
        [0.1723, 0.0430, 0.7949]])
tensor([[0.8493, 0.7954, 0.2022],
        [0.9894, 0.2137, 0.8185]])


In [67]:
m.add_(n)

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [68]:
print(m)
print("\n" + "-" * 40 + "\n")
print(n)

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

----------------------------------------

tensor([[0.8493, 0.7954, 0.2022],
        [0.9894, 0.2137, 0.8185]])


In [69]:
torch.relu(m)

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

In [70]:
m.relu_()

tensor([[1.8188, 1.3096, 0.8021],
        [1.1617, 0.2567, 1.6134]])

# **Copying a Tensor**

In [71]:
a = torch.rand(2,3)
print (a)

b = a

print(b)

tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])
tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])


In [72]:
id(a)

136901411727840

In [73]:
id(b)

136901411727840

In [74]:
# Cloning

b = a.clone()

In [75]:
print(a)

tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])


In [76]:
print(b)

tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])


In [77]:
a[0][0] = 10

In [78]:
print(a)

tensor([[10.0000,  0.6978,  0.4469],
        [ 0.7157,  0.8856,  0.0561]])


In [79]:
print(b)

tensor([[0.5125, 0.6978, 0.4469],
        [0.7157, 0.8856, 0.0561]])
